/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110577-ge076d8a9b3-20230513"
#endif /* AVUTIL_FFVERSION_H */
